"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time
from math import sqrt

start_time = time.time()
answer = None

# Code here
natural = 1
triangle = 0
while True:
    triangle = triangle + natural
    factors = set(
                reduce(
                    list.__add__,
                    ([i, triangle//i] for i in xrange(1, int(sqrt(triangle)) + 1) if triangle % i == 0)
                )
              )
    if len(factors) > 500:
        answer = triangle
        break

    natural += 1

# End timer
end_time = time.time()

print "Answer:   \t%d" % answer
print "Exec Time:\t%g microseconds\t%g seconds" % ((end_time - start_time) * 1000000, (end_time - start_time))
