"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import time

start_time = time.time()
answer = None

def evenfibs(num):
    a, b = 0, 1
    while True:
        if a > num:
            break
        if a % 2 == 0:
            yield a
        a, b = b, a + b

answer = sum([x for x in evenfibs(4000000)])

# End timer
end_time = time.time()

print "Answer:   \t%d" % answer
print "Exec Time:\t%g microseconds" % ((end_time - start_time) * 1000000)
